name: Tag & Release

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: true
      matrix:
        job:
          - runner: buildjet-4vcpu-ubuntu-2204
            arch: amd64
          - runner: buildjet-4vcpu-ubuntu-2204-arm
            arch: arm64

    name: Release - ${{ matrix.job.arch }}
    runs-on: ${{matrix.job.runner}}}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Semantic release
        uses: Greenroom-Robotics/ros_semantic_release_action@main
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          arch: ${{ matrix.job.arch }}
          public: true
          changelog: false