name: Tag & Release
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'The package to release.'
        options:
          - xtypes
      build_kilted:
        type: boolean
        default: true
        description: "Release for Kilted"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: greenroom-robotics/ros_semantic_release_action/.github/workflows/deb-pixi-release.yml@main
    with:
      package: ${{ inputs.package }}
      package_dir: .
      build_kilted: ${{ inputs.build_kilted }}
      changelog: false
      ros_distro: kilted
    secrets:
      token: ${{ secrets.API_TOKEN_GITHUB }}
      gh-app-client-id: ${{ secrets.GH_APP_CLIENT_ID }}
      gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
